#!/usr/bin/env python3
"""Generate platform catalogs from catalog.json. Run after editing translations."""
import json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
cat=json.loads((ROOT/'localization/catalog.json').read_text())
for key,values in cat.items():
    assert set(values)=={'en','zh'},key
    for text in values.values():
        assert text and sorted(re.findall(r'\{\d+\}',key))==sorted(re.findall(r'\{\d+\}',text)),key
payload=json.dumps(cat,ensure_ascii=False,separators=(',',':'))
def write(name,text):
    p=ROOT/name
    if '--check' in sys.argv:
        if not p.exists() or p.read_text() != text+'\n': raise SystemExit('Outdated localization artifact: '+name)
    else:
        p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text+'\n')
write('backend/web/assets/translations.js','// Generated by localization/generate.py\nglobalThis.SecretaryTranslations = '+payload+';')
write('macos/translations.json',payload)
write('android/app/src/main/assets/translations.json',payload)
if (ROOT/'ios/Secretary').exists():write('ios/Secretary/translations.json',payload)
# The extension only needs its own UI, not the entire application catalog.
extkeys=['AI Секретарь','Язык','Как в системе','Настройки']+[k for k in cat if 'SSO' in k or 'Расширение отключено.' in k]
write('browser-extension/src/translations.js','globalThis.SecretaryTranslations = '+json.dumps({k:cat[k] for k in extkeys},ensure_ascii=False)+';')

write('windows/internal/i18n/translations.json',payload)
mapping=json.loads((ROOT/'localization/windows-messages.json').read_text())
lines=['; Generated by localization/generate.py', '[CustomMessages]']
for key,source in mapping.items():
    for name,lang in [('russian','ru'),('english','en'),('chinese','zh')]:
        text=source if lang=='ru' else cat[source][lang]
        lines.append(name+'.'+key+'='+text.replace('\n','%n'))
write('windows/languages/custom-messages.iss','\n'.join(lines))
