package net.muratov.assistant

import android.graphics.BitmapFactory
import android.graphics.Bitmap
import net.muratov.assistant.data.ApiSession
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.runBlocking
import net.muratov.assistant.security.CompactIdentity
import com.google.zxing.DecodeHintType
import com.google.zxing.BinaryBitmap
import com.google.zxing.RGBLuminanceSource
import com.google.zxing.common.HybridBinarizer
import com.google.zxing.qrcode.QRCodeReader
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import net.muratov.assistant.security.AppClientIdentity
import net.muratov.assistant.security.GatewayIdentity
import net.muratov.assistant.security.GatewayMultiplexer
import net.muratov.assistant.security.GatewayTransport
import okhttp3.*
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.ByteArrayOutputStream
import java.io.File
import java.security.KeyStore
import java.security.cert.CertificateFactory
import java.util.Base64
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.zip.DeflaterOutputStream
import java.util.zip.InflaterInputStream
import javax.net.ssl.SSLContext
import javax.net.ssl.TrustManagerFactory
import javax.net.ssl.X509TrustManager

/** Fixtures are freshly generated by the Go protocol peer; no production secrets. */
@RunWith(AndroidJUnit4::class)
class GatewayConnectionTest {
    private val instrumentation = InstrumentationRegistry.getInstrumentation()
    private fun payload(): String {
        assumeTrue("Use -PgatewayFixtureDir with the Go test peer", instrumentation.context.assets.list("")!!.contains("mobile-qr.txt"))
        return instrumentation.context.assets.open("mobile-qr.txt").bufferedReader().use { it.readText() }
    }
    private fun pack(json: String): String {
        val out = ByteArrayOutputStream()
        DeflaterOutputStream(out).use { it.write(json.toByteArray()) }
        return GatewayIdentity.QR_PREFIX + Base64.getUrlEncoder().withoutPadding().encodeToString(out.toByteArray())
    }
    @Test fun recognizesGatewayAndRejectsInvalidBootstrapWithoutReplacingIdentity() {
        val payload = payload()
        val bitmap = instrumentation.context.assets.open("mobile-qr.png").use { BitmapFactory.decodeStream(it) }
        val pixels = IntArray(bitmap.width * bitmap.height)
        bitmap.getPixels(pixels, 0, bitmap.width, 0, 0, bitmap.width, bitmap.height)
        val scanned = QRCodeReader().decode(BinaryBitmap(HybridBinarizer(RGBLuminanceSource(bitmap.width, bitmap.height, pixels))), mapOf(DecodeHintType.TRY_HARDER to true)).text
        assertEquals(payload, scanned)
        for (available in listOf(360, 480)) {
            val modules = bitmap.width / 6
            val size = modules * (available / modules)
            val scaled = Bitmap.createScaledBitmap(bitmap, size, size, false)
            val scaledPixels = IntArray(size * size)
            scaled.getPixels(scaledPixels, 0, size, 0, 0, size, size)
            try {
                assertEquals(payload, QRCodeReader().decode(BinaryBitmap(HybridBinarizer(RGBLuminanceSource(size, size, scaledPixels))), mapOf(DecodeHintType.TRY_HARDER to true)).text)
            } catch (e: Exception) { throw AssertionError("Gateway QR at $size pixels", e) }
        }
        val context = instrumentation.targetContext
        val imported = AppClientIdentity.importQR(context, payload)
        val file = File(context.noBackupFilesDir, "gateway-identities/${imported.alias.removePrefix("gateway-identity:")}.json")
        try {
            assertTrue(GatewayIdentity.isAlias(imported.alias))
            assertFalse(AppClientIdentity.isAppAlias(imported.alias))
            val identity = GatewayIdentity.load(context, imported.server, imported.alias)
            assertEquals("11111111-1111-4111-8111-111111111111", identity.installation)
            val legacy = instrumentation.context.assets.open("legacy-qr.txt").bufferedReader().use { it.readText() }
            val oldIdentity = GatewayIdentity.parse(legacy)
            assertArrayEquals(oldIdentity.innerServerPin, identity.innerServerPin)
            assertArrayEquals(oldIdentity.cert.encoded, identity.cert.encoded)
            val fields = CompactIdentity.fields(payload, CompactIdentity.GATEWAY_PREFIX, 6)
            val badRole = fields.toMutableList().apply { this[1] = fields[4] }
            assertThrows(IllegalArgumentException::class.java) { AppClientIdentity.importQR(context, compactTestPayload(CompactIdentity.GATEWAY_PREFIX, badRole)) }
            val badKey = fields.toMutableList().apply { this[2] = fields[5] }
            assertThrows(IllegalArgumentException::class.java) { AppClientIdentity.importQR(context, compactTestPayload(CompactIdentity.GATEWAY_PREFIX, badKey)) }
            assertThrows(IllegalArgumentException::class.java) { AppClientIdentity.importQR(context, compactTestRaw(CompactIdentity.GATEWAY_PREFIX, ByteArray(16385))) }
            val json = JSONObject(InflaterInputStream(Base64.getUrlDecoder().decode(legacy.removePrefix(GatewayIdentity.QR_PREFIX)).inputStream()).bufferedReader().use { it.readText() })
            json.put("installation_id", "22222222-2222-4222-8222-222222222222")
            assertThrows(IllegalArgumentException::class.java) { AppClientIdentity.importQR(context, pack(json.toString())) }
            json.put("installation_id", identity.installation).put("key", json.getString("inner_key"))
            assertThrows(IllegalArgumentException::class.java) { AppClientIdentity.importQR(context, pack(json.toString())) }
            assertThrows(IllegalArgumentException::class.java) { AppClientIdentity.importQR(context, pack("x".repeat(16385))) }
            assertThrows(IllegalArgumentException::class.java) { AppClientIdentity.importQR(context, payload.replace(":G2:", ":G3:")) }
            assertTrue(file.isFile)
            assertEquals(identity.installation, GatewayIdentity.load(context, imported.server, imported.alias).installation)
        } finally { file.delete() }
    }
    @Test fun innerTLSCarriesHTTPAndRealtimeAcrossGateway() {
        val identity = GatewayIdentity.parse(payload())
        val legacy = instrumentation.context.assets.open("legacy-qr.txt").bufferedReader().use { it.readText() }
        val json = JSONObject(InflaterInputStream(Base64.getUrlDecoder().decode(legacy.removePrefix(GatewayIdentity.QR_PREFIX)).inputStream()).bufferedReader().use { it.readText() })
        val serverCert = CertificateFactory.getInstance("X.509").generateCertificate(Base64.getUrlDecoder().decode(json.getString("inner_server")).inputStream()) as java.security.cert.X509Certificate
        GatewayIdentity.trustServer(identity).checkServerTrusted(arrayOf(serverCert), "EC")
        assertThrows(java.security.cert.CertificateException::class.java) {
            GatewayIdentity.trustServer(identity.copy(innerServerPin = ByteArray(32))).checkServerTrusted(arrayOf(serverCert), "EC")
        }
        val outer = trustedOuter(identity)
        val client = GatewayTransport.client(identity, outer)
        try {
            client.newCall(Request.Builder().url("${identity.gateway}/api/v1/system/status").build()).execute().use {
                assertEquals(200, it.code)
                assertEquals("gateway", JSONObject(it.body.string()).getString("transport"))
            }
            val received = CountDownLatch(1)
            var result: String? = null
            var failure: Throwable? = null
            val socket = client.newWebSocket(Request.Builder().url("${identity.gateway}/api/v1/realtime").build(), object : WebSocketListener() {
                override fun onOpen(webSocket: WebSocket, response: Response) { webSocket.send("realtime-through-inner-tls") }
                override fun onMessage(webSocket: WebSocket, text: String) { result = text; received.countDown() }
                override fun onFailure(webSocket: WebSocket, t: Throwable, response: Response?) { failure = t; received.countDown() }
            })
            try {
                assertTrue("Realtime timeout", received.await(30, TimeUnit.SECONDS))
                failure?.let { throw AssertionError("Realtime failed", it) }
                assertEquals("realtime-through-inner-tls", result)
            } finally { socket.cancel() }
        } finally {
            client.connectionPool.evictAll(); client.dispatcher.executorService.shutdown()
            GatewayMultiplexer.close()
            outer.connectionPool.evictAll(); outer.dispatcher.executorService.shutdown()
        }
    }
    private fun trustedOuter(identity: GatewayIdentity.Identity): OkHttpClient {
        val ca = instrumentation.context.assets.open("gateway-ca.crt").use { CertificateFactory.getInstance("X.509").generateCertificate(it) }
        val store = KeyStore.getInstance(KeyStore.getDefaultType()).apply { load(null); setCertificateEntry("test-ca", ca) }
        val trust = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm()).apply { init(store) }.trustManagers.filterIsInstance<X509TrustManager>().single()
        val ssl = SSLContext.getInstance("TLS").apply { init(GatewayIdentity.keyManagers(identity.cert, identity.key), arrayOf(trust), null) }
        return GatewayTransport.externalClient(identity).newBuilder().sslSocketFactory(ssl.socketFactory, trust).build()
    }

    @Test fun gatewayStreamLimitReportsHTTP429AndRecoversAfterClosingPools() = runBlocking {
        val identity = GatewayIdentity.parse(payload())
        val outer = trustedOuter(identity)
        val clients = mutableListOf<OkHttpClient>()
        try {
            // Reproduce the previous repository behavior: a separate pool per request.
            repeat(32) {
                val client = GatewayTransport.client(identity, outer, multiplex = false).also { clients += it }
                client.newCall(Request.Builder().url("${identity.gateway}/api/v1/system/status").build())
                    .execute().use { assertEquals(200, it.code); it.body.string() }
            }
            val overflow = GatewayTransport.client(identity, outer, multiplex = false).also { clients += it }
            val error = assertThrows(java.io.IOException::class.java) {
                overflow.newCall(Request.Builder().url("${identity.gateway}/api/v1/system/status").build())
                    .execute().close()
            }
            assertTrue(error.toString(), error.message.orEmpty().contains("HTTP 429"))
        } finally {
            clients.forEach { it.connectionPool.evictAll(); it.dispatcher.executorService.shutdown() }
            val deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(5)
            var active: Int
            do {
                active = outer.newCall(Request.Builder().url("${identity.gateway}/test/tunnel-stats").build())
                    .execute().use { JSONObject(it.body.string()).getInt("active") }
                if (active > 0) Thread.sleep(50)
            } while (active > 0 && System.nanoTime() < deadline)
            try {
                assertEquals(0, active)
                ApiSession { _, _ -> GatewayTransport.client(identity, outer, multiplex = false) }.use {
                    assertEquals("ok", it.get(identity.gateway, "recovered").systemStatus().overallStatus)
                }
            } finally { GatewayMultiplexer.close(); outer.connectionPool.evictAll(); outer.dispatcher.executorService.shutdown() }
        }
    }

    @Test fun apiRequestsReuseTunnelsAndReleaseThemWhenConnectionChanges() = runBlocking {
        val identity = GatewayIdentity.parse(payload())
        val outer = trustedOuter(identity)
        val clients = mutableListOf<OkHttpClient>()
        val session = ApiSession { _, _ ->
            GatewayTransport.client(identity, outer).also { clients += it }
        }
        fun stats(): JSONObject = outer.newCall(
            Request.Builder().url("${identity.gateway}/test/tunnel-stats").build(),
        ).execute().use { assertEquals(200, it.code); JSONObject(it.body.string()) }
        val openedBefore = stats().getInt("opened")
        try {
            // The old per-request client exhausts all 32 gateway slots here.
            repeat(96) {
                assertEquals("ok", session.get(identity.gateway, "first").systemStatus().overallStatus)
            }
            assertEquals("Sequential API requests should use one tunnel", 1, stats().getInt("opened") - openedBefore)
            assertEquals(1, clients.size)
            (1..8).map {
                async {
                    repeat(8) {
                        assertEquals("ok", session.get(identity.gateway, "first").systemStatus().overallStatus)
                    }
                }
            }.awaitAll()
            assertTrue("Concurrent requests should share one physical tunnel", stats().getInt("opened") - openedBefore == 1)

            // Realtime owns its own client; stopping it must not shut down the API pool.
            val realtime = GatewayTransport.client(identity, outer)
            realtime.connectionPool.evictAll()
            realtime.dispatcher.executorService.shutdown()
            assertEquals("ok", session.get(identity.gateway, "first").systemStatus().overallStatus)

            // Certificate replacement at the same URL must release the old pool.
            assertEquals("ok", session.get(identity.gateway, "replacement").systemStatus().overallStatus)
            assertEquals(2, clients.size)
            assertEquals(0, clients[0].connectionPool.connectionCount())
            assertTrue(clients[0].dispatcher.executorService.isShutdown)
            // Switching server addresses must also rebuild the client.
            val otherHost = identity.gateway.replace("127.0.0.1", "localhost")
            session.get(otherHost, "replacement")
            assertEquals(3, clients.size)
            assertTrue(clients[1].dispatcher.executorService.isShutdown)
        } finally {
            session.close()
            val deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(5)
            while (stats().getInt("active") > 0 && System.nanoTime() < deadline) Thread.sleep(50)
            try { assertEquals("Closed pools must release gateway slots", 0, stats().getInt("active")) }
            finally { GatewayMultiplexer.close(); outer.connectionPool.evictAll(); outer.dispatcher.executorService.shutdown() }
        }
    }

    @Test fun singleTunnelCarriesParallelAPIRealtimeCancellationAndReconnect() = runBlocking {
        val identity = GatewayIdentity.parse(payload())
        GatewayMultiplexer.close()
        val outer = trustedOuter(identity)
        val api = GatewayTransport.client(identity, outer)
        val realtime = GatewayTransport.client(identity, outer)
        val clients = mutableListOf(api, realtime)
        fun stats(): JSONObject = outer.newCall(Request.Builder().url("${identity.gateway}/test/tunnel-stats").build())
            .execute().use { JSONObject(it.body.string()) }
        val before = stats().getInt("opened")
        val opened = CountDownLatch(1)
        val received = java.util.concurrent.LinkedBlockingQueue<String>()
        val failures = java.util.concurrent.LinkedBlockingQueue<Throwable>()
        val socket = realtime.newWebSocket(Request.Builder().url("${identity.gateway}/api/v1/realtime").build(), object : WebSocketListener() {
            override fun onOpen(webSocket: WebSocket, response: Response) { opened.countDown() }
            override fun onMessage(webSocket: WebSocket, text: String) { received.add(text) }
            override fun onFailure(webSocket: WebSocket, t: Throwable, response: Response?) { failures.add(t); opened.countDown() }
        })
        try {
            // Cold-start API races realtime and separate clients, yet opens only one WSS.
            (1..8).map {
                async(Dispatchers.IO) {
                    val client = GatewayTransport.client(identity, outer)
                    synchronized(clients) { clients += client }
                    repeat(4) {
                        client.newCall(Request.Builder().url("${identity.gateway}/api/v1/system/status").build())
                            .execute().use { assertEquals(200, it.code); it.body.string() }
                    }
                }
            }.awaitAll()
            assertTrue(opened.await(20, TimeUnit.SECONDS))
            assertTrue(failures.toString(), failures.isEmpty())
            assertEquals(1, stats().getInt("opened") - before)
            assertEquals(1, stats().getInt("active"))
            socket.send("before-upload")
            assertEquals("before-upload", received.poll(10, TimeUnit.SECONDS))

            val bytes = ByteArray(2 * 1024 * 1024) { (it % 251).toByte() }
            val upload = async(Dispatchers.IO) {
                api.newCall(Request.Builder().url("${identity.gateway}/test/echo").post(bytes.toRequestBody()).build())
                    .execute().use { assertEquals(200, it.code); assertArrayEquals(bytes, it.body.bytes()) }
            }
            socket.send("during-upload")
            assertEquals("during-upload", received.poll(10, TimeUnit.SECONDS))
            upload.await()
            val waiting = api.newCall(Request.Builder().url("${identity.gateway}/test/wait").build())
            val cancelled = CountDownLatch(1)
            waiting.enqueue(object : Callback {
                override fun onResponse(call: Call, response: Response) { response.close(); cancelled.countDown() }
                override fun onFailure(call: Call, e: java.io.IOException) { cancelled.countDown() }
            })
            Thread.sleep(200)
            waiting.cancel()
            assertTrue(cancelled.await(10, TimeUnit.SECONDS))
            socket.send("after-cancel")
            assertEquals("after-cancel", received.poll(10, TimeUnit.SECONDS))
            assertEquals(1, stats().getInt("opened") - before)

            outer.newCall(Request.Builder().url("${identity.gateway}/test/drop-tunnels").post(ByteArray(0).toRequestBody()).build())
                .execute().use { assertEquals(204, it.code) }
            assertNotNull("Realtime must observe tunnel loss", failures.poll(10, TimeUnit.SECONDS))
            clients.forEach { it.connectionPool.evictAll() }
            api.newCall(Request.Builder().url("${identity.gateway}/api/v1/system/status").build())
                .execute().use { assertEquals(200, it.code); it.body.string() }
            assertEquals("Reconnect creates exactly one replacement tunnel", 2, stats().getInt("opened") - before)
            assertEquals(1, stats().getInt("active"))
        } finally {
            socket.cancel()
            clients.forEach { it.connectionPool.evictAll(); it.dispatcher.executorService.shutdown() }
            GatewayMultiplexer.close()
            outer.connectionPool.evictAll(); outer.dispatcher.executorService.shutdown()
        }
    }

}
